# ==================================
# Exclude list file for Kagami.sh
# ==================================
#
# This file specifies patterns for files and directories to exclude from backup.
# rsync's `--exclude-from` option reads this file,
# so rsync pattern syntax applies.
#
# For more details, see the "Include/Exclude Pattern Rules" section in:
# https://linux.die.net/man/1/rsync

# You can use comments starting with `#`.

# Directories
node_modules/
.git/

# Files
*.log

# Specific directories or files
/home/USER/Downloads/*.zip
