#!/bin/bash

# =======================================================
# Kagami.sh - My backup tool that works on my machine.
# =======================================================
#
# Copyright (c) 2025-2025 Rinrin.rs
# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

VERSION=$(git describe --tags --always --dirty 2>/dev/null)
if [ $? -ne 0 ]; then
    VERSION="(unknown version)"
fi

# Check for required external commands.
for cmd in rsync realpath grep tput find mv rm mkdir tr printf date tee; do
    command -v "$cmd" >/dev/null 2>&1 || {
        echo -e "\033[31mERROR: Required command not found: $cmd\033[0m"
        exit 1
    }
done

# Generate a unique run identifier for this execution.
# This is used for both log files and trash directories.
RUN_ID="$(date '+%Y%m%d_%H%M%S')_$$"

# ▼ Utility Functions ▼

print_error() {
    if [[ -t 1 ]]; then
        echo -e "\033[31mERROR: $1\033[0m"
    else
        echo "ERROR: $1"
    fi
}

TERM_WIDTH="${COLUMNS:-$(tput cols 2>/dev/null || echo 70)}"
print_separator() {
    printf '%*s\n' "$TERM_WIDTH" '' | tr ' ' '-'
}

# Check whether `$1` is a subdirectory of `$2`.
# Use `realpath` to resolve symlinks for accurate comparison.
is_subdirectory_of() {
    local child parent
    child="$(realpath -m "$1")"
    parent="$(realpath -m "$2")"
    # Normalize trailing slash for prefix matching.
    parent="${parent%/}/"
    [[ "$child" == "$parent"* ]]
}

# ▲ Utility Functions ▲

# Load the configuration file.
SCRIPT_DIR="$(dirname "$(realpath "$0")")"
CONFIG_FILE="$SCRIPT_DIR/kagami.conf"
if [[ ! -f "$CONFIG_FILE" ]]; then
    print_error "Configuration file not found: $CONFIG_FILE"
    exit 1
fi
source "$CONFIG_FILE"

# Validate that mandatory configuration variables are set.
if [[ -z "$DEST" ]] || [[ -z "$TRASH_RETENTION_DAYS" ]]; then
    print_error "Configuration variables DEST and TRASH_RETENTION_DAYS must be set in $CONFIG_FILE."
    exit 1
fi

# Validate that `$TRASH_RETENTION_DAYS` is a positive integer.
if ! [[ "$TRASH_RETENTION_DAYS" =~ ^[0-9]+$ ]]; then
    print_error "TRASH_RETENTION_DAYS must be a positive integer."
    exit 1
fi

# Check for `dry` argument in command-line arguments to enable dry-run mode.
VALID_ARGS_MSG="Valid commands: none or \"dry\""
DRY_RUN_FLAG=""
# If more than one argument is provided, show an error.
if [[ $# -gt 1 ]]; then
    print_error "Unknown command. $VALID_ARGS_MSG"
    exit 1
# If exactly one argument is provided, check if it is a valid argument.
elif [[ $# -eq 1 ]]; then
    if [[ "$1" == "dry" ]]; then
        DRY_RUN_FLAG="--dry-run"
        echo -e "\033[33m========================================\033[0m"
        echo -e "\033[33m DRY RUN MODE: No changes will be made. \033[0m"
        echo -e "\033[33m========================================\033[0m"
        echo
    else
        print_error "Unknown command \"$1\". $VALID_ARGS_MSG"
        exit 1
    fi
fi

# Normalize `$DEST` to ensure consistency (resolve symlinks and remove trailing slash).
DEST="$(realpath -m "$DEST")"
# Remove trailing slash for consistency.
DEST="${DEST%/}"

# Safety check: Refuse to use critical system directories or their subdirectories as backup destination.
# This prevents catastrophic data loss if `$DEST` is misconfigured.
#
# FORBIDDEN_SUBTREE_MATCHES: The entire directory tree under these paths is forbidden.
# This is for critical system paths like /usr, /var, and the user's own home directory.
FORBIDDEN_SUBTREE_MATCHES=(
    "/bin" "/boot" "/dev" "/etc" "/lib" "/lib64" "/proc"
    "/root" "/sbin" "/sys" "/usr" "/var" "/.snapshots"
)
# FORBIDDEN_EXACT_MATCHES: Only the exact path is forbidden, but subdirectories are allowed.
# This is for generic mount points like /mnt or /media, where a user might mount a backup drive.
FORBIDDEN_EXACT_MATCHES=("/" "/home" "/media" "/mnt" "/opt" "/run" "/run/media" "/srv" "/tmp" "$HOME")
for dangerous in "${FORBIDDEN_SUBTREE_MATCHES[@]}"; do
    if is_subdirectory_of "$DEST" "$dangerous"; then
        print_error "Refusing to use a subdirectory of a critical system path as backup destination: $DEST (inside $dangerous)"
        exit 1
    fi
done
for dangerous in "${FORBIDDEN_EXACT_MATCHES[@]}"; do
    if [[ "$(realpath -m "$DEST")" == "$(realpath -m "$dangerous")" ]]; then
        print_error "Refusing to use a root-level or generic mount point as backup destination: $DEST"
        exit 1
    fi
done

# Check whether the backup destination directory `$DEST` exists.
if [[ ! -d "$DEST" ]]; then
    print_error "Backup destination directory not found: $DEST"
    exit 1
fi

# Check for the manifest file that serves as a backup destination identifier.
# This prevents accidental operations on uninitialized directories.
MANIFEST_HEADER="# DO NOT EDIT THIS FILE MANUALLY.
# This file was automatically generated by Kagami.sh.
# Run ID: $RUN_ID"
MANIFEST_FILE="$DEST/.kagami-manifest"
MANIFEST_JUST_CREATED=false
if [[ ! -f "$MANIFEST_FILE" ]]; then
    echo "The backup destination has not been initialized: $DEST"
    echo "The manifest file \`.kagami-manifest\` is required to identify this as a valid backup destination."
    echo

    # Check whether the script is running interactively (stdin attached to a terminal).
    if [[ -t 0 ]]; then
        read -rp "Initialize this directory as a backup destination? [y/N]: " response
        case "$response" in
            [yY]|[yY][eE][sS])
                if [[ -z "$DRY_RUN_FLAG" ]]; then
                    echo "$MANIFEST_HEADER" > "$MANIFEST_FILE"
                fi
                MANIFEST_JUST_CREATED=true
                echo "Initialized: $MANIFEST_FILE"
                echo
                ;;
            *)
                echo "Aborted by the user."
                exit 1
                ;;
        esac
    else
        # Non-interactive mode (e.g., cron job): refuse to proceed.
        print_error "Cannot initialize in non-interactive mode."
        echo "Please run this script manually first to initialize the backup destination."
        exit 1
    fi
fi

# Set up logging to save all output to a log file.
LOG_BASE_DIR="$DEST/.kagami-logs"
LOG_FILE="$LOG_BASE_DIR/$RUN_ID.log"
if [[ -z "$DRY_RUN_FLAG" ]]; then
    mkdir -p "$LOG_BASE_DIR" || {
        print_error "Failed to create log directory: $LOG_BASE_DIR"
        exit 1
    }
    exec > >(tee -a "$LOG_FILE") 2>&1
fi

echo "[ Kagami.sh $VERSION ]"
echo

# Show the previous run ID only if this is not a freshly initialized manifest.
if [[ "$MANIFEST_JUST_CREATED" == "false" ]]; then
    PREV_RUN_ID="$(grep -m 1 '^# Run ID: ' "$MANIFEST_FILE" 2>/dev/null | sed 's/^# Run ID: //')"
    if [[ -z "$PREV_RUN_ID" ]]; then
        echo "Last backup run ID: N/A"
    else
        echo "Last backup run ID: $PREV_RUN_ID"
    fi
fi

TARGET_LIST_FILE_NAME="targets.conf"
TARGETS="$SCRIPT_DIR/$TARGET_LIST_FILE_NAME"

# Check for the target list file `$TARGETS` (i.e. `$TARGET_LIST_FILE_NAME`).
if [[ ! -f "$TARGETS" ]]; then
    print_error "Target list file not found."
    echo "Please create a file named \`$TARGET_LIST_FILE_NAME\` in the same directory as this script:"
    echo $TARGETS
    exit 1
fi

# Load the exclude list file if it exists.
EXCLUDE_LIST_FILE_NAME="excludes.conf"
EXCLUDES_FILE="$SCRIPT_DIR/$EXCLUDE_LIST_FILE_NAME"
EXCLUDE_FROM_FLAG=""
if [[ -f "$EXCLUDES_FILE" ]]; then
    EXCLUDE_FROM_FLAG="--exclude-from=$EXCLUDES_FILE"
fi

echo "Starting backup to: $DEST"
echo "Run ID: $RUN_ID"
echo

FAILED_TARGETS=()
CURRENT_TARGETS=()

# Read the target list file line by line.
# Skip empty lines and comment lines that start with `#`.
while read -r line || [[ -n "$line" ]]; do
    print_separator

    # Replace leading tilde (`~`) with `$HOME`.
    # Example: `~/Pictures` -> `$HOME/Pictures`.
    SOURCE_PATH="${line/#\~/$HOME}"

    # Trim leading and trailing whitespace from `$SOURCE_PATH`.
    SOURCE_PATH="${SOURCE_PATH#"${SOURCE_PATH%%[![:space:]]*}"}"
    SOURCE_PATH="${SOURCE_PATH%"${SOURCE_PATH##*[![:space:]]}"}"

    # Normalize `$SOURCE_PATH` to an absolute path to prevent path traversal attacks.
    # This ensures relative paths like `../project` are resolved correctly.
    # It also prevents cleanup from deleting files outside the backup destination.
    SOURCE_PATH="$(realpath -m "$SOURCE_PATH")"

    CURRENT_TARGETS+=("${SOURCE_PATH%/}")

    # Check whether `$SOURCE_PATH` exists; skip if it does not.
    if [[ ! -e "$SOURCE_PATH" ]]; then
        echo "Skipping: $SOURCE_PATH (not found)"
        FAILED_TARGETS+=("$SOURCE_PATH (not found)")
        continue
    fi

    echo "Syncing: $SOURCE_PATH"

    # Run `rsync`.
    #
    # - `-a`: Archive mode (`-rlptgoD`)
    # - `-v`: Verbose output (shows files being transferred)
    # - `-h`: Human-readable numbers (outputs sizes in KB, MB, GB)
    # - `-R`: Relative paths (preserves full directory structure at destination)
    # - `--delete-delay`: Finds extraneous files from dest dirs and deletes after
    # - `--delete-excluded`: Also delete excluded files from dest dirs
    # - `--exclude`: Exclude files matching the pattern
    #
    # Note: `$EXCLUDE_FROM_FLAG` will be either empty or `--exclude-from=excludes.conf` depending on whether the exclude list file exists.
    #
    # - `--exclude-from`: Read exclude patterns from a file (supports comments with `#`)
    #
    # Note: `$DRY_RUN_FLAG` will be either empty or `--dry-run` depending on the command-line argument.
    #
    # - `--dry-run`: Dry run mode (performs a trial run with no changes made)
    rsync -avhR --delete-delay --delete-excluded --exclude='.kagami-manifest' $EXCLUDE_FROM_FLAG $DRY_RUN_FLAG -- "$SOURCE_PATH" "$DEST"
    RSYNC_EXIT_CODE=$?

    # Verify whether `rsync` completed successfully.
    if [[ $RSYNC_EXIT_CODE -ne 0 ]]; then
        print_error "rsync failed for \`$SOURCE_PATH\` with exit code: $RSYNC_EXIT_CODE"
        FAILED_TARGETS+=("$SOURCE_PATH (rsync failed with exit code: $RSYNC_EXIT_CODE)")
    fi
done < <(grep -Ev '^[[:space:]]*($|#)' "$TARGETS")
print_separator

# Clean up stale backups (targets that were removed from the list).
TRASH_BASE_DIR="$DEST/.kagami-trash"
TRASH_DIR="$TRASH_BASE_DIR/$RUN_ID"
TRASH_CREATED=false
if [[ -f "$MANIFEST_FILE" ]]; then
    while IFS= read -r prev; do
        # Check whether the previous target is still in the current list.
        found=false
        for curr in "${CURRENT_TARGETS[@]}"; do
            if [[ "$prev" == "$curr" ]]; then
                found=true
                break
            fi
        done

        # If not found, it means the target was removed from the list.
        if [[ "$found" == "false" ]]; then
            # Check whether this path is a subdirectory of any current target.
            # If so, skip deletion since it will be backed up as part of the parent.
            is_covered=false
            for curr in "${CURRENT_TARGETS[@]}"; do
                if is_subdirectory_of "$prev" "$curr"; then
                    is_covered=true
                    break
                fi
            done
            if [[ "$is_covered" == "true" ]]; then
                echo "Skipping cleaning up of stale target (covered by current target): $prev"
                continue
            fi

            # Check whether any current target is a subdirectory of this stale target.
            contains_active_target=false
            for curr in "${CURRENT_TARGETS[@]}"; do
                if is_subdirectory_of "$curr" "$prev"; then
                    contains_active_target=true
                    break
                fi
            done
            if [[ "$contains_active_target" == "true" ]]; then
                echo "Skipping cleaning up of stale target (contains active target): $prev"
                continue
            fi

            # Remove the leading slash to construct the path inside `$DEST`.
            REL_PATH="${prev#/}"
            REMOVE_PATH="$DEST/$REL_PATH"

            # Verify that `$REMOVE_PATH` is inside the backup destination `$DEST`.
            # This prevents accidental deletion of files outside `$DEST` due to malformed
            # paths in the manifest (e.g., paths containing `..` or other traversal attempts).
            if ! is_subdirectory_of "$REMOVE_PATH" "$DEST"; then
                print_error "Refusing to delete path outside backup destination: $REMOVE_PATH"
                FAILED_TARGETS+=("$prev (cleanup refused: outside backup destination)")
                continue
            fi

            if [[ -e "$REMOVE_PATH" ]]; then
                echo -e "\033[33mCleaning up stale target: $REMOVE_PATH\033[0m"
                if [[ -z "$DRY_RUN_FLAG" ]]; then
                    # Create the trash directory on first use.
                    if [[ "$TRASH_CREATED" == "false" ]]; then
                        mkdir -p "$TRASH_DIR"
                        TRASH_CREATED=true
                    fi
                    TRASH_TARGET="$TRASH_DIR/$REL_PATH"
                    mkdir -p "$(dirname "$TRASH_TARGET")"
                    mv "$REMOVE_PATH" "$TRASH_TARGET"
                fi
            fi
        fi
    done < <(grep -Ev '^[[:space:]]*($|#)' "$MANIFEST_FILE")
fi

# Update the manifest file with the current list of targets.
if [[ -z "$DRY_RUN_FLAG" ]]; then
    {
        echo "$MANIFEST_HEADER"
        printf "%s\n" "${CURRENT_TARGETS[@]}"
    } > "$MANIFEST_FILE"
fi

# Clean up old trash directories.
if [[ -d "$TRASH_BASE_DIR" ]]; then
    while IFS= read -r -d '' old_trash; do
        echo "Deleting old trash: $old_trash"
        if [[ -z "$DRY_RUN_FLAG" ]]; then
            rm -rf "$old_trash"
        fi
    done < <(find "$TRASH_BASE_DIR" -mindepth 1 -maxdepth 1 -type d -mtime +"$TRASH_RETENTION_DAYS" -print0)

    # If the trash base directory `$TRASH_BASE_DIR` is empty, remove it.
    if [[ -z "$DRY_RUN_FLAG" ]] && [[ -d "$TRASH_BASE_DIR" ]]; then
        rmdir "$TRASH_BASE_DIR" 2>/dev/null || true
    fi
fi

echo
if [[ -n "$DRY_RUN_FLAG" ]]; then
    echo "Dry run completed."
else
    echo "All backups completed."
fi

# Report any failed targets.
if [[ ${#FAILED_TARGETS[@]} -gt 0 ]]; then
    echo
    print_error "The following targets had issues:"
    printf '  - %s\n' "${FAILED_TARGETS[@]}"
    exit 2
fi
