# ===================================
# Configuration file for Kagami.sh
# ===================================

# Backup destination directory.
#
# To check available space and filesystem type,
# you can use the command: `df -hT`
#
# Warning: The directory you specify below will be used as the ROOT of the backup destination.
#          An incorrect setting may overwrite or remove data within the chosen path.
DEST="/run/media/USER/FOO-DRIVE/kagami-backups/"

# Number of days to retain files in the trash.
TRASH_RETENTION_DAYS=30
