# =================================
# Target list file for Kagami.sh
# =================================

/etc

# You can use comments starting with `#`.

# You can use `~/` to represent the home directory.
~/Pictures
~/Videos/Screencasts

# You can specify individual files as targets.
~/.bashrc
